allOf:
  - $ref: "./productVariantUpdate.yaml"
  - type: object
    properties:
      id:
        type: string
      product_id:
        type: string

  # media:
  #   type: array
  #   items:
  #     type: string
  # price:
  #   type: string
  # stock:
  #   type: integer
  # warrenty_time:
  #   type: number
