type: object
properties:
  media:
    type: array
    items:
      type: string
  price:
    type: string
  stock:
    type: integer
  status:
    type: string
    enum:
      - active
      - inactive
  warrenty_time:
    type: number
