type: object
properties:
  title:
    type: string
  media:
    type: array
    items:
      type: string
  options:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        values:
          type: array
          items: string
  sizing_guide:
    type: string
  details:
    type: string
  status:
    type: boolean
