openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "Outfit Orbit API documentation"
  description: "Outfit Orbit API documentation using OpenAPI and Swagger UI"
components:
  securitySchemes:
    oAuthSample: # <---- arbitrary name
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow. [More info](https://api.example.com/docs/auth)
      flows:
        implicit: # <---- OAuth flow(authorizationCode, implicit, password or clientCredentials)
          authorizationUrl: https://api.example.com/oauth2/authorize
          scopes:
            read_pets: read your pets
            write_pets: modify pets in your account
security:
  - oAuthSample:
      - write_pets
      - read_pets
paths:
  /login:
    post:
      summary: "Login to OutFit Orbit and establish a session"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                password:
                  type: string
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
  /register:
    post:
      summary: "Register an account"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                password:
                  type: string
                email:
                  type: string
                phone:
                  type: string
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
  /forgotpassword:
    post:
      summary: "Forgot password to a certain account, trigger email for resetting password"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                email:
                  type: string
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
  /home/recommended:
    $ref: "./home.yaml#/paths/~1recommended"
  /home/popular:
    $ref: "./home.yaml#/paths/~1popular"
  /home/followed:
    $ref: "./home.yaml#/paths/~1followed"
  /search:

  /carts:
    $ref: "./carts.yaml#/paths/~1carts"
  /carts/add:
    $ref: "./carts.yaml#/paths/~1carts~1add"
  /carts/delete:
    $ref: "./carts.yaml#/paths/~1carts~1delete"
  /carts/edit:
    $ref: "./carts.yaml#/paths/~1carts~1edit"
  /products/{id}/general:
    $ref: "./products.yaml#/paths/~1products~1{id}~1general"
  /products/{id}/variant:
    $ref: "./products.yaml#/paths/~1products~1{id}~1variant"
  /topics:
    $ref: "./topics.yaml#/paths/~1topics"
  /topics/{id}:
    $ref: "./topics.yaml#/paths/~1topics~1{id}"
