openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "Outfit Orbit API documentation"
  description: "Outfit Orbit API documentation using OpenAPI and Swagger UI"
components:
  securitySchemes:
    oAuthSample:    # <---- arbitrary name
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow. [More info](https://api.example.com/docs/auth)
      flows:
        implicit:   # <---- OAuth flow(authorizationCode, implicit, password or clientCredentials)
          authorizationUrl: https://api.example.com/oauth2/authorize
          scopes:
            read_pets: read your pets
            write_pets: modify pets in your account
security: 
  - oAuthSample: 
    - write_pets
    - read_pets
paths:
  /login:
    post:
      summary: "Login to OutFit Orbit and establish a session"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                password:
                  type: string
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
  /register:
    post:
      summary: "Register an account"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                password:
                  type: string
                email:
                  type: string
                phone:
                  type: string
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
  /forgotpassword:
    post:
      summary: "Forgot password to a certain account, trigger email for resetting password"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                email:
                  type: string
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
  /home/recommended:
    $ref: './homePage.yaml#/paths/~1recommended'
  /home/hot:
    $ref: './homePage.yaml#/paths/~1hot'
  /cart:
    $ref: './cart.yaml#/paths/~1cart'
  /cart/add:
    $ref: './cart.yaml#/paths/~1cart~1add'
    