openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "Outfit Orbit API documentation"
  description: "Outfit Orbit API documentation using OpenAPI and Swagger UI"
paths:
  /login:
    post:
      summary: "Login to OutFit Orbit and establish a session"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                password:
                  type: string
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
  /register:
    post:
      summary: "Register an account"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                password:
                  type: string
                email:
                  type: string
                phone:
                  type: string
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
  /forgotpassword:
    post:
      summary: "Forgot password to a certain account, trigger email for resetting password"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                email:
                  type: string
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
  /home/recommended:
    $ref: './home.yaml#/paths/~1recommended'
  /home/hot:
    $ref: './home.yaml#/paths/~1hot'
    