openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "Outfit Orbit API documentation"
  description: "Outfit Orbit API documentation using OpenAPI and Swagger UI"
servers:
  - url: "https://demo.identityserver.io/api"
    description: "Identity Server API"
components:
  securitySchemes:
    # See https://demo.identityserver.io/ for configuration details.
    identity_server_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "https://demo.identityserver.io/connect/authorize"
          scopes:
            api: "api"
security:
  - identity_server_auth:
    - api
paths:
  /login:
    post:
      summary: "Login to OutFit Orbit and establish a session"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                password:
                  type: string
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"