openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "Outfit Orbit API documentation for Home page"
  description: "Outfit Orbit API documentation using OpenAPI and Swagger UI"
paths: 
  /cart:
    get:
      summary: "Get the shopping cart for a customer"
      parameters:
        - in: query
          name: customer_id
          schema: 
            type: string
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: './components/shoppingCart.yaml'
  /cart/add:
    post:
      summary: "Add a number of product variants to a customers"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id: 
                  type: string
                product_id:
                  type: string
                variant_id:
                  type: string
                count:
                  type: integer  
      responses:
        200:
          description: "OK"