openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "Outfit Orbit API documentation for Home page"
  description: "Outfit Orbit API documentation using OpenAPI and Swagger UI"
paths:
  /carts/{id}:
    get:
      summary: "Get the shopping cart for a customer"
      parameter:
        - in: path
          required: true
          name: id
          schema:
            type: string
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "./components/shoppingCart.yaml"
    delete:
      summary: "Delete product variant from a customer's cart"
      parameter:
        - in: path
          required: true
          name: id
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: string
                variant_id:
                  type: string
      responses:
        200:
          description: "OK"
  /carts/{id}/add:
    put:
      summary: "Add items to a customer's cart"
      parameter:
        - in: path
          required: true
          name: id
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: string
                variant_id:
                  type: string
                count:
                  type: integer
      responses:
        200:
          description: "OK"
  /carts/{id}/edit:
    put:
      summary: "Edit a product variant's count in a customer's cart"
      parameter:
        - in: path
          required: true
          name: id
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: string
                variant_id:
                  type: string
                count:
                  type: integer
      responses:
        200:
          description: "OK"
