openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "Outfit Orbit API documentation for Home page"
  description: "Outfit Orbit API documentation using OpenAPI and Swagger UI"
paths:
  /carts:
    get:
      summary: "Get the shopping cart for a customer"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "./components/shoppingCart.yaml"

  /carts/add:
    put:
      summary: "Add items to a customer's cart"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                product_id:
                  type: string
                variant_id:
                  type: string
                count:
                  type: integer
      responses:
        200:
          description: "OK"
  /carts/delete:
    delete:
      summary: "Delete product variant from a customer's cart"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                product_id:
                  type: string
                variant_id:
                  type: string
      responses:
        200:
          description: "OK"
  /carts/edit:
    put:
      summary: "Edit a product variant's count in a customer's cart"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                product_id:
                  type: string
                variant_id:
                  type: string
                count:
                  type: integer
      responses:
        200:
          description: "OK"
