openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "Outfit Orbit API documentation for Home page"
  description: "Outfit Orbit API documentation using OpenAPI and Swagger UI"
paths: 
  /recommended:
    get:
      summary: "Get a sorted list of recommended posts"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: string
                scrolled_through_post_id:
                  type: array
                  items: 
                    type: string
                locale:
                  type: string
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: './components/postTiles.yaml'
  /hot:
    get:
      summary: "Get a sorted list of hot posts"
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: './components/postTiles.yaml'
  /followed:
    get:
      summary: "Get a sorted list of followed posts"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: string
                scrolled_through_post_id:
                  type: array
                  items: 
                    type: string
                locale:
                  type: string
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: './components/postTiles.yaml'