openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "Outfit Orbit API documentation for Home page"
  description: "Outfit Orbit API documentation using OpenAPI and Swagger UI"
paths:
  /explore:
    get:
      summary: "Get a sorted list of 9 recommended posts"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: string
                locale:
                  type: string
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./components/postTile.yaml"
  /popular:
    get:
      summary: "Get a segment of sorted list of popular posts"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                locale:
                  type: string
                start:
                  type: integer
                count:
                  type: integer
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./components/postTile.yaml"
  /follow:
    get:
      summary: "Get a segment of sorted list of followed posts"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: string
                start:
                  type: integer
                count:
                  type: integer
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./components/postTile.yaml"
