openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "Outfit Orbit API documentation for Home page"
  description: "Outfit Orbit API documentation using OpenAPI and Swagger UI"
paths:
  /products:
    post:
      summary: "Post the general information of a product"
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: string
      responses:
        200:
          description: "OK"
  /products/{id}:
    get:
      summary: "Get the general information of a product"
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: string
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "./components/productGeneral.yaml"
    put:
    delete:
      summary: "Delete the all information of a product"
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: string
      responses:
        200:
          description: "OK"
  /products/{id}/variant:
    get:
      summary: "Get variant specific information of a product with given option values"
      parameters:
        - in: query
          name: option_values
          schema:
            type: object
            additionalProperties:
              type: string
          style: form
          explode: true
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "./components/productVariant.yaml"
    put:
