openapi: 3.0.0
info:
  version: 0.0.1
  title: Outfit Orbit API documentation
  description: Outfit Orbit API documentation using OpenAPI and Swagger UI
paths:
  /login:
    post:
      summary: Login to OutFit Orbit and establish a session
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /register:
    post:
      summary: Register an account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                password:
                  type: string
                email:
                  type: string
                phone:
                  type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /forgotpassword:
    post:
      summary: >-
        Forgot password to a certain account, trigger email for resetting
        password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /home/recommended:
    get:
      summary: Get a sorted list of recommended posts
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: string
                scrolled_through_post_id:
                  type: array
                  items:
                    type: string
                locale:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '401':
          description: Unauthorized
